environment = "dev"
environment_name = "dev"
location = "westeurope"
resource_group_name = "rg-data-dev"
vnet_name = "vnet-data-dev"
subnet_names = ["subnet-app", "subnet-db", "subnet-integration"]
storage_account_name = "stdataappdev"
storage_account_tier = "Standard"
storage_account_replication = "LRS"
key_vault_name = "kv-data-dev"
sql_server_name = "sql-data-dev"
sql_admin_login = "sqladmin"
sql_admin_password = "Password@123"
data_factory_name = "df-data-dev"
databricks_workspace_name = "dbw-data-dev"
databricks_sku = "premium"
client_id = "d8152502-96f6-4401-91cf-9658dd9e830d"
client_secret = "REPLACE_WITH_SECRET"
tenant_id = "1658af60-3667-462c-8c0e-8ee391b6cab8"
subscription_id = "f5545c7c-1f71-4924-8e15-14cde7221be9"

# Unity Catalog variables
databricks_workspace_id = "1234567890-dev-wsid"
access_connector_id     = "connector-id-dev-abc123"
